### ISSUE TITLE
PAR2

### ISSUE THREAD

**Issue by ghost** [tgulacsi/par#1]
Have you managed to add PAR2 creation yet? :-)

Looking for a faster PAR2 creation alternative. Fastest I've found so far is https://github.com/animetosho/ParPar but the Reed Solomon implementation of github.com/klauspost/reedsolomon looks promising.

**Comment by tgulacsi** [comment]
I can create PAR2-like parity info with this program, but couldn't make it compatible with the "par2" program.

**Comment by ghost** [comment]
Okay. Thanks.
